site_name: PT. Tunas Mitra Sejati
theme: readthedocs
nav:
  - Selamat Datang: index.md
  - Alur Sistem: alursistem.md
  - Akses Aplikasi: akses.md
  - Dashboard: dashboard.md
  - Equipment: equipment.md
  - Survey: survey.md
  - Safety: safety.md
  - Purchase Requisition: purchase-requisition.md
  - Procurement: procurement.md
  - Finance: finance.md
  - Approval: approval.md
  - Master Data: master-data.md
  - Setting: setting.md
markdown_extensions:
  - attr_list
